@startuml

title UML-діаграма активності для запису відчуття

start

:Споживач обирає опцію "Записати відчуття";

repeat
  :Споживач вибирає емоцію або пише іншу;
  :Споживач додає коментар;

  if (Дані коректні?) then (Так)
    :Збереження відчуття та емоції у системі;
    stop
  else (Ні)
    :Виведення повідомлення про помилку;
    :Споживач наново редагує коментар та обирає емоцію;
  endif
repeat while (Дані не збережені)

@enduml
