@startuml

title Use Case Diagram

left to right direction

actor Споживач
rectangle "Програма" {
    usecase (Запис емоцій та відчуттів)
    usecase (Перегляд статистики емоцій)
    
    Споживач -- (Запис емоцій та відчуттів)
    Споживач -- (Перегляд статистики емоцій)
    (Перегляд статистики емоцій) .> (Запис емоцій та відчуттів) : include
}

@enduml
