@startuml

title UML-діаграма активності

start

:Споживач обирає опцію "Записати емоцію та коментар";


  :Споживач вибирає емоцію або пише іншу;
  :Споживач додає коментар;

repeat
  if (Дані коректні?) then (Так)
    :Збереження відчуття та емоції у системі;
    stop
  else (Ні)
    :Виведення повідомлення про помилку;
    :Споживач наново редагує коментар та обирає емоцію;
  endif
:Дані не збережені;
repeat while ();

@enduml
